### ISSUE TITLE
Demo App: you should be able to cancel editing image attributes.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-Aztec-iOS#120]
When in the image-attributes VC: there should be an option to cancel editing image attributes, that closes the VC without it affecting the HTML.

**Comment by SergioEstevao** [comment]
I think this ticket description is a bit confusing, reading this I thought you where talking on the existence of a cancel button on the image VC.

Do you mean the possibility of not setting a specific attribute to any value?

**Comment by diegoreymendez** [comment]
Actually your initial interpretation is right, this is only about adding a cancel button to the VC.

I'm not sure we should allow removing attributes from images in visual mode.  In fact, the web editor in Calypso doesn't allow that.

**Comment by diegoreymendez** [comment]
This is currently possible actually.  Closing.
