### ISSUE TITLE
Blockquote render incorrectly with dark mode

### ISSUE THREAD

**Issue by WestFlow127** [wordpress-mobile/WordPress-Aztec-iOS#1301]
**Describe the bug**
The block quote background is a shade of white while the text is white as well. (Text is the dynamic color: UIColor.label)

**To Reproduce**
1. Set textColor to 'UIColor.Label' and switch to dark mode. (background color should be set to UIColor.systemBackground)
2. Click on the toggleBlockQuote button to create a block quote.
3. Type some text in.

**Expected behavior**
The background of the block quote should be darker, such as 'systemFill' or 'secondarySystemFill'
Some kind of medium-dark greyish background possibly with an alpha less than 1.

**Screenshots**
<img width="416" alt="Screen Shot 2020-08-03 at 4 50 15 PM" src="https://user-images.githubusercontent.com/13974119/89238320-7dcd8900-d5aa-11ea-92f8-4279c7ae66e7.png">

**Smartphone (please complete the following information):**
 - iPhone 11 Pro simulator
 - OS: iOS 13.6
 - Aztec Version 1.19.2

**Comment by WestFlow127** [comment]
Can someone please look at this or give me insight on how this can be resolved?

**Comment by WestFlow127** [comment]
Bump!

**Comment by geriux** [comment]
Hey there @WestFlow127  👋 

You can customize the background of the Blockquote with `blockquoteBackgroundColor`, see this [example](https://github.com/wordpress-mobile/AztecEditor-iOS/blob/develop/Example/Example/EditorDemoController.swift#L180-L183).

Does that work for the issue you have?

Let us know, thanks!

**Comment by WestFlow127** [comment]
Hey @geriux 

Ahh yes! that works, thank you.
