### ISSUE TITLE
Missing li tags when switching list style

### ISSUE THREAD

**Issue by tipa** [wordpress-mobile/WordPress-Aztec-iOS#1307]
**Describe the bug**
The Aztec editor does not add li tags when changing the list style of an existing list

**To Reproduce**
1. Open demo App
2. Click on 'Empy Demo'
3. Enter 3 lines of an unordered list
4. select middle line and change it to ordered list
5. switch to code editor view

**Expected behavior**
```
<ul>
  <li>line 1</li>
</ul>
<ol>
  <li>line 2</li>
</ol>
<ul>
  <li>line 3</li>
</ul>
```

**Actual behavior**
```
<ul>
  <li>line 1</li>
</ul>
<ol>line 2</ol>
<ul>
  <li>line 3</li>
</ul>
```

**Smartphone (please complete the following information):**
 - Device:  iPhone6S
 - OS: iOS14.1

**Comment by elangbamjohnson** [comment]
I have a fix for this and ready to put a PR.

**Comment by hypest** [comment]
EDIT: managed to replicate the issue.

<details>
<summary>Previous version of my comment</summary>
Hmm, I can't replicate the issue on develop (). Here are the steps I follow:
1. Open the demo app
2. Switch to html mode, delete everything, switch back to visual mode
3. Start an unordered bullet list
4. Put in a few lines via the virtual keyboard
5. Place the cursor on the second line
6. Switch the list type via the toolbar
7. Switch to html mode

At that stage what I see in the html mode is:
```
<ol>
 <li>Line1</li>
 <li>Line2</li>
 <li>Line3</li>
</ol>
```

So, unless there are some other steps to reproduce, I'm proposing to close this ticket.

Thanks for opening a PR @elangbamjohnson ! Do you perhaps have some updated steps for how to reproduce the issue? Thanks!
</details>
