### ISSUE TITLE
the example can not run on xcode12 iPhone simulator12pro max14.2

### ISSUE THREAD

**Issue by 463292462** [wordpress-mobile/WordPress-Aztec-iOS#1313]
download this project and then terminal 
Downloads/AztecEditor-iOS-develop/Example
carthage update --platform iOS
*** Cloning Gridicons-iOS
*** Checking out Gridicons-iOS at "1.0"
*** xcodebuild output can be found in /var/folders/cf/ff_gvm196wbdr8lxq64t0y9h0000gn/T/carthage-xcodebuild.sWydy2.log
*** Building scheme "Gridicons" in Gridicons.xcworkspace

Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Library/Caches/org.carthage.CarthageKit/DerivedData/12.2_12B45b/Gridicons-iOS/1.0/Build/Intermediates.noindex/ArchiveIntermediates/Gridicons/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Gridicons.framework/Gridicons /Library/Caches/org.carthage.CarthageKit/DerivedData/12.2_12B45b/Gridicons-iOS/1.0/Build/Products/Release-iphonesimulator/Gridicons.framework/Gridicons -output /Downloads/AztecEditor-iOS-develop/Example/Carthage/Build/iOS/Gridicons.framework/Gridicons

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/cf/ff_gvm196wbdr8lxq64t0y9h0000gn/T/carthage-xcodebuild.sWydy2.log

**Comment by guarani** [comment]
Thanks for raising this. It looks like this is an issue with Carthage (the dependency manager) and Xcode 12. Please see https://github.com/Carthage/Carthage/issues/3019#issuecomment-665136323 for more information (note, the steps described there should be done in the `Example` sub-directory).

Does that fix the issue for you?

**Comment by 463292462** [comment]
Thank you. This solves my problem
