### ISSUE TITLE
Question: Does this editor support MacOS?

### ISSUE THREAD

**Issue by imsai-sh** [wordpress-mobile/WordPress-Aztec-iOS#1324]
I'm looking for a rich text editor that can support IOS and MAC . Does this editor support Mac OS? What is the minimum required version? Or  plan to support it in the future? like "AztecEditor-MacOS"....
Thank you!

**Comment by guarani** [comment]
There is no official support for macOS at the moment and I don't think it's on the roadmap. I [enabled Mac](https://developer.apple.com/documentation/xcode/creating_a_mac_version_of_your_ipad_app?language=objc) and ran the project and although it ran, it's clear there are a few things that would need investigating. The main format toolbar doesn't appear for example, and there might be other issues too.

<img width="1011" alt="Screen Shot 2021-02-24 at 10 20 05" src="https://user-images.githubusercontent.com/1898325/109007220-aa520b00-768a-11eb-86c9-b1f57ac8dad0.png">

**Comment by imsai-sh** [comment]
> There is no official support for macOS at the moment and I don't think it's on the roadmap. I [enabled Mac](https://developer.apple.com/documentation/xcode/creating_a_mac_version_of_your_ipad_app?language=objc) and ran the project and although it ran, it's clear there are a few things that would need investigating. The main format toolbar doesn't appear for example, and there might be other issues too.
> 
> <img alt="Screen Shot 2021-02-24 at 10 20 05" width="1011" src="https://user-images.githubusercontent.com/1898325/109007220-aa520b00-768a-11eb-86c9-b1f57ac8dad0.png">

Thanks for your reply . And I also tried to run the app on Mac according to the link you gave.This solved my question.
