### ISSUE TITLE
Issue regarding toggling between order list and unordered list. I have solution for that please check the description box

### ISSUE THREAD

**Issue by amolPawar1221** [wordpress-mobile/WordPress-Aztec-iOS#1343]
Before toggling to list li tag we can check is li tag present for range or not.

Check the photo
![1639472795095148008420](https://user-images.githubusercontent.com/35678843/145967514-ab4d3267-9411-4e09-b06b-1bb6cbd9437b.jpg)

**Comment by hypest** [comment]
Thanks for reaching out @amolPawar1221 !

I'd be best if you can open a Pull Request with your proposal. Ideally, the PR will include a description of the solution and steps to reproduce the issue and how verify to the fix. There are some [information about contributing in this post](https://github.com/wordpress-mobile/AztecEditor-iOS/blob/develop/CONTRIBUTING.md). It will be easier for the devs to pick up reviewing your suggestion via a PR.

In the meantime, I'll go ahead and close this ticket to allow for the discussion to move to more actionable formats. That said, feel free to open a ticket to describe the issue (not the solution) at hand, if such a ticket doesn't exist yet. Thanks!
