### ISSUE TITLE
Improve caret calculation

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-Aztec-iOS#143]
In #142 we added a quick fix to fix an issue where the caret would disappear when positioned at the end of the text. This works for now, but I think it's a sign that we're not calculating it the right way, so let's revisit that.

We currently take the default implementation and make it fit the line fragment vertically. But, when the cursor is at the end (or the editor is empty) there's no glyph to calculate a line for, so the line fragment is an empty rect.

The original custom code was meant to fix huge carets on paragraphs with spacing:

![simulator screen shot 9 nov 2016 11 17 54](https://cloud.githubusercontent.com/assets/8739/20135076/36ec05a8-a66e-11e6-9016-7742c251daa7.png)
![simulator screen shot 9 nov 2016 11 18 03](https://cloud.githubusercontent.com/assets/8739/20135077/371b9a16-a66e-11e6-9690-e96dd48a872c.png)

**Comment by diegoreymendez** [comment]
I'm closing this for now as it does not apply to the current code base.
