### ISSUE TITLE
Custom attributes removed on new line

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-Aztec-iOS#145]
When you are at the end of a blockquote and type return, the new line doesn't have the right background. It seems like UITextView is dropping the custom `Blockquote` attribute but keeping the paragraph style.

**Comment by diegoreymendez** [comment]
@SergioEstevao - Can this one be closed?

**Comment by diegoreymendez** [comment]
I'm closing this one as it's no longer present in the code base.  It was indirectly fixed by other changes we implemented.
