### ISSUE TITLE
New line isn't being saved <br>

### ISSUE THREAD

**Issue by JackHM** [wordpress-mobile/WordPress-Aztec-iOS#164]
Hello,

I have been playing with the demo app, and have to say the keyboard etc is fantastic! Noticed a little issue not sure, it might be me?!

Basically in the editor demo, when you type some text and jump down a few lines and then type some more, after doing that if you go to the html tab/textView and then go back to the native the whiteSpaces and new lines are not saved?

Is this correct? If it is please do excuse me!

**Comment by diegoreymendez** [comment]
Thanks for the report.

There's still quite a bit of work to do regarding whitespace in the editor, but this is one of the known issues with it.

We'll probably be reviewing all of our open tickets next week, so this may end up becoming part of a larger task.  Meanwhile I'll leave it open as a reminder.

Thanks for the report, and let us know if there's anything else.  The help with testing is welcome!

**Comment by diegoreymendez** [comment]
Resolved.
