### ISSUE TITLE
Undo: Data Loss

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-Aztec-iOS#193]
### Steps:
1. Launch the demo App and open the **Editor Demo**
2. Locate and delete the `Underlined Text` words
3. Shake + Undo
4. Switch to the HTML view, and back to the Native

As a result, the `Underlined Text` words will be lost.

cc @diegoreymendez

**Comment by diegoreymendez** [comment]
This seems to have been fixed indirectly.  Closing.
