### ISSUE TITLE
Lists: Lost Style

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-Aztec-iOS#211]
#### Steps
1. Open the `Empty Editor` demo
2. Toggle Ordered List
3. Hit `Return` twice
4. Verify that the Ordered List gets closed
5. Hit the `Ordered List` button again
6. Type anything

Note that as a result, the ordered list will get lost.

![missing-style](https://cloud.githubusercontent.com/assets/1195260/21594446/e7eb4876-d109-11e6-8fda-87fe1b4555e8.gif)

**Comment by jleandroperez** [comment]
**Note for further reference:**
- Empty Lists can / should use the Zero Width Placeholder
- Whenever the list becomes **non empty**, we should definitely nuke this empty placeholder.

**Comment by diegoreymendez** [comment]
This seems to have been fixed indirectly.
