### ISSUE TITLE
Insert Link: Prefill URL field with clipboard contents if appropriate

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Aztec-iOS#250]
It would be nice if the editor was smart enough to recognize when the clipboard contains a URL, and pre-fill that field when inserting a link.  The common flow is to open the browser, copy a link, and then switch back to the WordPress app to insert it in a post.

**Comment by diegoreymendez** [comment]
@hoverduck - This was implemented by @SergioEstevao and will be available in 0.5b2.
