### ISSUE TITLE
There's no way to interrupt adding a link.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-Aztec-iOS#251]
When adding a link, the style is never interrupted.  There's simply no mechanism to do so.

<H3>Steps to reproduce</h3>

1. Open the empty editor.
2. Insert a link.
3. Continue typing... you'll notice there's no way to interrupt the link style.

**Comment by SergioEstevao** [comment]
I was looking at calypso to see how they solve this, and it looks that for links if you get to the end of the range where the link was applied the property stops automatically.

@diegoreymendez do you think that will be a good solution?

**Comment by diegoreymendez** [comment]
@SergioEstevao - Yes.  Also, we need to make it so the link style button can be turned off manually.

Both are required IMHO for this issue.
