### ISSUE TITLE
There's no way to remove a link.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-Aztec-iOS#265]
<h3>Description:</h3>

Currently there's no way to remove a link.  The link button always tries to add one even when the caret is on top of an existing link.

Related to #251 .

**Comment by SergioEstevao** [comment]
On the alert controller that shows up you have the option to "remove link". Do you want to make the link icon to switch to the remove link button where you have the cursor on top of the link?

**Comment by diegoreymendez** [comment]
Actually, no.  My initial idea of turning the button into a toggle is a bad one.

I just checked out Calypso and I think we just need to make sure the link string attribute is never extended when you're standing at the end of it.

Sounds good?

**Comment by diegoreymendez** [comment]
This is no longer an issue.
