### ISSUE TITLE
Title field should scroll when scrolling content

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/WordPress-Aztec-iOS#273]
Comment from tester:

> As a side note, I also found it surprising that the post title was pinned to the top of the editor in iOS, even when my keyboard was open. This only left a small space for me to see the post content I was editing.

**Comment by rachelmcr** [comment]
This is especially an issue when I try to write a post in landscape view. I can only see one line of text at a time (and only when predictive text is disabled on my keyboard):

![2017-02-17 16 28 03](https://cloud.githubusercontent.com/assets/8658164/23075180/63932e56-f533-11e6-8442-1e17fa1746b5.png)

It's pretty much impossible for me to write in landscape with such a small view of the screen.

Here's the same post in the visual editor, where the post title scrolls off the screen:

![2017-02-17 16 27 30](https://cloud.githubusercontent.com/assets/8658164/23075204/79386104-f533-11e6-8c33-887d613f3830.png)

This is on an iPhone 6, iOS 10.2.1, WPiOS 7.0.0.20170214.

**Comment by jleandroperez** [comment]
Closing this one in favor of its [WPiOS counterpart](https://github.com/wordpress-mobile/WordPress-iOS/issues/6680).

Thank you both!
