### ISSUE TITLE
Extra lines on lists

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/WordPress-Aztec-iOS#277]
Regular lists (no nested list items) on iOS has extra blank items between each line:

![screen-shot-2017-02-15-at-12-27-02-pm](https://cloud.githubusercontent.com/assets/651601/22978684/9e28145e-f38b-11e6-8559-2812525da7fa.png)

**Comment by jleandroperez** [comment]
Tested in Develop // closing as cannot repro.
Thanks!!
