### ISSUE TITLE
Switching sites from Page Editor incorrectly publishes Posts

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Aztec-iOS#323]
1) Create a new Page (not post)
2) Use the site selector at the top of the editor to change sites

Note that now the button at the upper right says "Post" instead of "Publish".  Clicking that will publish the content as a Post on the selected site instead of a Page.

I was unable to reproduce this on the legacy editor, so I'm assuming it's an Aztec initial state issue

**Comment by diegoreymendez** [comment]
@hoverduck - For all bugs related to testing in WPiOS, please submit to the WPiOS repo with the "Aztec" tag.  The Aztec devs will take care of forwarding anything that's rooted in the Aztec-core.

I've moved this issue [here]().

Thanks for the report!
