### ISSUE TITLE
How do I integrate it with my project?

### ISSUE THREAD

**Issue by dannyjeong421** [wordpress-mobile/WordPress-Aztec-iOS#328]
I am trying to have the HTML editor demo part in my iOS app written by Swift. Could anybody walk me through the detail process to do it please?

**Comment by diegoreymendez** [comment]
Have you tried inspecting the `AztecExample` project?

The idea is to use that project as the starting point for 3rd party Apps.   You can simply copy the VC `EditorDemoController.swift` and modify it to suit your needs.

Of course, you'll also need to install the Aztec pod using CocoaPods.

Let us know if there's anything more specific you need help with.

**Comment by dannyjeong421** [comment]
Thank you for your help, @diegoreymendez.

Yes I was able to run the `AztecExample` project on the simulator through `carthage update`. I tried to add the framwork into my existing project using Carthage and it didn't work(Build failed). I have tried to open the  `AztecExample` project using CocoaPods and it didn't work.

It would be great to have step by step introduction to add framework using Carthage or to add Pod using CocoaPods into my project.

**Comment by diegoreymendez** [comment]
#dannyjeong421 - I created [an issue](https://github.com/wordpress-mobile/WordPress-Aztec-iOS/issues/334) to track progress on your documentation request.

This will be ready sometimes in our beta cycle.  The timeline is not set in stone yet, but you could check back with us in a couple of weeks.

In the meantime: if you want to start experimenting with Aztec, you can include this line in your App's `podfile`:

```
pod 'WordPress-Aztec-iOS', '0.5a5'
```

Then you can run `pod install` normally to install the library.

Consider copying the example View Controller from this project named `EditorDemoController.swift` into your App, and use it as a starting point.

Let me know if you have any questions.

**Comment by dannyjeong421** [comment]
@diegoreymendez  Sounds awesome!! I will try it out. Thanks much for your help!

**Comment by dannyjeong421** [comment]
Thanks @diegoreymendez! It's working great! I will close it for now. :)

**Comment by diegoreymendez** [comment]
My pleasure!
