### ISSUE TITLE
Padding around images

### ISSUE THREAD

**Issue by 0nko** [wordpress-mobile/WordPress-Aztec-iOS#331]
When adding multiple images to a post, they appear right on top of each other. Also, it's difficult to position the cursor before or after an image.

![image](https://cloud.githubusercontent.com/assets/1522856/23411433/9521b7c4-fdd2-11e6-9534-583bf3e5c48b.png)

**Comment by SergioEstevao** [comment]
@diegoreymendez  to create spacing we will need to add a space or new lines character around images. 
I don't think this should be the default of the insertImage in TextView but when reacting to the command of the toolbar we could insert the image and add space around it. 

This can be even more critical when we are inserting multiples images in one go in a post.

**Comment by diegoreymendez** [comment]
@SergioEstevao - Any thoughts on either adding white padding to images programmatically or modifying the layout code to do just that?

I think we should be able to achieve a good result without adding actual characters.

**Comment by SergioEstevao** [comment]
We can add white space around the image when generating the glyph, so that
visually it will look better.

But the thing is that for the layout system that attachment always take the
full space.

So it's always going to be hard for the user to put cursor on the middle of
two images.
