### ISSUE TITLE
Ordered and unordered lists.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-Aztec-iOS#34]
Enable the lists button and add the logic to edit lists in the editor.  List behavior is as follows:
### Toolbar:
- [x] OL button should highlight when cursor is in an order list
- [x] UL button should highlight when cursor is in an unordered list
#### Tapping a List Button:
- [x] **Scenario 1**: When the cursor is in a plain paragraph: 
  `Should create a new list, and turn the whole paragraph into a list item.`
- [x] **Scenario 2**: When the cursor is in a list of the same type: 
  `Should turn the item into a plain paragraph. Following list items should be renumbered.`
- [x] **Scenario 3**: When the cursor is in a list of a different type: 
  `Should change the type of the entire list, and update the list markers appropriately.`
- [x] **Scenario 4:** When the selected text starts with a paragraph then intersects a list of the same type: 
  `Should add the non-list text to the list and update the item numbering.`
- [x] **Scenario 5:** When the selected text starts with a paragraph then intersects a list of a different type: 
  `Should create a new list from the selected paragraph, but do not make changes to the other list.`
- [x] **Scenario 6:** When the selected text starts with a list of the same type and intersects a non-list paragraph: 
  `Should Remove the list.`
- [x] **Scenario 7:** When the selected text starts with a list of a different type and intersects a non-list paragraph:
  `Should change the type of the list and update its numbering, but make no changes to the non list paragraph.`
### Selection:
- [x] **Scenario 1:** Whenever there was no previous selected text (just the cursor blinking on a line), and a List was applied, the cursor should shift to match the spot at which it was previously located. In another words: we should apply a delta, to consider the new Text Marker.
- [x] **Scenario 2:** Whenever a list is applied over a Selected Range, we should expand the selection to consider any length-deltas, caused by Text Markers.
### Cursor:
- [x] If the current selection intersects a list marker, adjust the selection so it does not intersect the marker.  Move the cursor forward or backward depending on the previous cursor location.
### Typing:
- [x] Apply the current list and list item custom attributes to newly typed text (keyboard input does not automatically assign custom attributes.)
### Carriage returns:
- [x] When there is a carriage return inside a list. Insert a new list marker.  Update the numbering of any following items. 
- [x] When the cursor is on an empty list item (just the marker and no other text) and a carriage return is added.  Remove the empty list item, and insert a normal paragraph in its place.  If there are any following list items, replace those items with a new list and new item numbering. 
### Backspace / Delete:
- [x] When a backspace would intersect a list marker, delete the entire list marker + the carriage return of the preceding list item (if any).  If the current list item still had text, merge the remaining text with the previous list item. Update the numbering for any following items.

**Comment by diegoreymendez** [comment]
I've unchecked all the previously-checked items, since @jleandroperez is going to start bringing them into separate PRs one by one.

The reason why we're taking this approach is to be able to incrementally advance our progress on this.  The master ticket is too big to try and solve all at once.

**Comment by jleandroperez** [comment]
Thank you @diegoreymendez!!

**Comment by diegoreymendez** [comment]
I'm closing this ticket as ordered and unordered lists have been implemented.  Anything else coming up going forwards will be treated as bug reports.
