### ISSUE TITLE
How to focus and blur?

### ISSUE THREAD

**Issue by musicode** [wordpress-mobile/WordPress-Aztec-iOS#340]
Any methods can I call?

**Comment by diegoreymendez** [comment]
I believe `.becomeFirstResponder()` and `.resignFirstResponder()` should work.  Can you try those out?

**Comment by musicode** [comment]
yes, it works

**Comment by chrishawn** [comment]
in the example code i add
`richTextView.becomeFirstResponder()`
to the `viewDidLoad()`
and the keyboard shows and then is hidden again? tried tracking down why and could not find why.

**Comment by chrishawn** [comment]
nevermind found it was `traitCollectionDidChange()`
