### ISSUE TITLE
Crash: Strikethrough + Blockquote

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-Aztec-iOS#350]
### Steps:
1. Launch the empty editor
2. Toggle Strikethru
3. Toggle Blockquote

Crash onscreen!
cc @diegoreymendez 

<img width="1220" alt="screen shot 2017-03-09 at 2 00 12 pm" src="https://cloud.githubusercontent.com/assets/1195260/23761198/c1340ea2-04d0-11e7-9f0f-2eb0aa1576e2.png">

**Comment by diegoreymendez** [comment]
To whoever ends up tackling this issue: make sure to include the unit test from branch `issue/350-crash`, which tests exactly for this issue

**Comment by SergioEstevao** [comment]
This also happens with other character formatters like: Bold, Italic, Underline, etc..

**Comment by diegoreymendez** [comment]
Fixed.
