### ISSUE TITLE
Unknown HTML support in visual mode.

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/WordPress-Aztec-iOS#369]
At the moment if the content has a non supported tag like:

<span>
<table>
<video>

We are simple ignoring tag and not showing anything on the visual representation.

Following the Android implementation we should detect these tags and show a ? character (or maybe something like the name of the tag. Ex: ```<table>```. And allow users visualise it's content.

**Comment by diegoreymendez** [comment]
@SergioEstevao - Sorry for changing the title but I wanted to make sure "unknown HTML support" was on it, to make it easier to spot.
