### ISSUE TITLE
Title does not stay with end of text while typing if it extends past screen width

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Aztec-iOS#385]
![img_3578](https://cloud.githubusercontent.com/assets/1158819/24182357/9ba9fedc-0e7e-11e7-868f-8e9b120fe2c7.PNG)

The full title is "What Steven Ballmer and I have in common", yet the text field doesn't show the end of the title while typing.

@diegoreymendez I'm only assigning you since you're leading iOS and know how to prioritize this. Feel free to pass this off to anyone.

**Comment by diegoreymendez** [comment]
Thanks for the report @kwonye !

**Comment by SergioEstevao** [comment]
On the current hybrid editor this automatically expands the title text view to a new line.
