### ISSUE TITLE
Cannot change heading style once set.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-Aztec-iOS#399]
As reported by @rachelmcr:

Once you select a heading (e.g. “Heading 1”) for text in Aztec, any further changes to the heading selection affect the visual mode but don’t change the HTML on the post.

Steps to reproduce:

1. Open Aztec and enter some text (e.g. “text”).
2. Select the text and set it as “Heading 1.”
3. Switch to HTML mode and note that the correct HTML is applied (`<h1>text</h1>`).
4. With the same text selected, set it as “Heading 2.”
5. Switch to HTML mode again.

Result: The HTML still has the original setting (`<h1>text</h1>`) instead of the expected change (`<h2>text</h2>`).

Tested on iPhone 6, iOS 10.2.1, WPiOS 7.2.0.20170317 with Aztec editor enabled.

**Comment by SergioEstevao** [comment]
Confirmed this is bug, I will tackle this.
