### ISSUE TITLE
Self closing tags are not being written properly

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/WordPress-Aztec-iOS#51]
If you have html content with tags that are self closing/empty tags like this:

```
<img src="a.jpg" />
<br/>
```

they get converted back to

```
<img src="a.jpg">
<br>
```

and even if you have something like this:

```
<img src="a.jpg">Imagem</img>
```

It gets converted to 

`<img src="a.jpg">`

**Comment by diegoreymendez** [comment]
@SergioEstevao - I'm closing this issue as even if the exact initial representation is indeed not maintained, we can accept the difference for now, and it shouldn't cause any real issues.

Feel free to reopen if we find evidence that this change is necessary, or if this turns out to cause issues.
