### ISSUE TITLE
Selection causes the default font to change.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-Aztec-iOS#58]
There's a very weird bug that's causing the Visual Editor default font to change, if you select a styled text-range and switch to HTML and back to Visual.

Video showing the issue [here](https://cloudup.com/cyBYbeDF2fv).

**Comment by SergioEstevao** [comment]
When working o this PR: https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1221 I realized that the font assigned to the TextView changes when you move the selection around the textview and it's set to whatever is configured in the attributedString at the current caret location!!
